### PR TITLE
Update locales.rb with belarusian language

### PR DESCRIPTION
**Pull request by kirylrb**
Add Belarusian language

### CODE REVIEW

**Comment by kirylrb** [comment]
@gschlager please take a look

**Comment by gschlager** [comment]
Thanks! Are you going to create a pull request to add Belarusian to Discourse as well?
https://meta.discourse.org/t/how-to-add-a-new-language/14970

**Comment by kirylrb** [comment]
@gschlager As I understand it's already there in repo
```be: { i18n: { plural: { keys: [:one, :few, :many, :other], rule: lambda { |n| n % 10 == 1 && n % 100 != 11 ? :one : [2, 3, 4].include?(n % 10) && ![12, 13, 14].include?(n % 100) ? :few : n % 10 == 0 || [5, 6, 7, 8, 9].include?(n % 10) || [11, 12, 13, 14].include?(n % 100) ? :many : :other } } } },```

https://github.com/discourse/discourse/blob/master/config/locales/plurals.rb

**Comment by gschlager** [comment]
The plural rules are just a small part. There's a whole process of adding a new language. See https://meta.discourse.org/t/how-to-add-a-new-language/14970

I'm sorry, I can't merge this PR without the other stuff. You are welcome to submit a PR to the main discourse repository as well as long as you follow all the steps in the topic mentioned above. Otherwise this will have to wait a couple of days until we find the time to add the language.

**Comment by kirylrb** [comment]
@gschlager Provided link don't exist, sorry.
I've opened the PR based on examples, please check https://github.com/discourse/discourse/pull/7777

**Pull request merged**
